import { useEffect, useState, useCallback } from 'react';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import { updatePostSummary, updatePostDifficulty } from '@/store/blogSlice';
import { aiService } from '@/services/aiService';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Lightbulb, Loader2, Brain, Zap } from 'lucide-react';

interface AISummaryProps {
  postId: string;
  content: string;
}

const AISummary = ({ postId, content }: AISummaryProps) => {
  const dispatch = useAppDispatch();
  const post = useAppSelector((state) =>
    state.blog.posts.find(p => p.id === postId)
  );
  const [isGenerating, setIsGenerating] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showSummary, setShowSummary] = useState(false);

  // Generate AI summary
  const handleGenerateSummary = async () => {
    if (post?.summary) {
      setShowSummary(!showSummary);
      return;
    }

    setIsGenerating(true);
    try {
      const summary = await aiService.generateSummary(content, {
        maxLength: 150,
        style: 'concise'
      });
      dispatch(updatePostSummary({ postId, summary }));
      setShowSummary(true);
    } catch (error) {
      console.error('Failed to generate summary:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  // Analyze reading difficulty
  const handleAnalyzeDifficulty = useCallback(async () => {
    if (post?.difficulty) return;

    setIsAnalyzing(true);
    try {
      const difficulty = await aiService.analyzeReadingDifficulty(content);
      dispatch(updatePostDifficulty({ postId, difficulty }));
    } catch (error) {
      console.error('Failed to analyze difficulty:', error);
    } finally {
      setIsAnalyzing(false);
    }
  }, [post?.difficulty, content, dispatch, postId]);

  // Auto-analyze difficulty on mount if not already analyzed
  useEffect(() => {
    if (post && !post.difficulty && content) {
      handleAnalyzeDifficulty();
    }
  }, [post, content, handleAnalyzeDifficulty]);

  if (!post) return null;

  if (!post) return null;

  return (
    <Card className="mb-6 border-l-4 border-l-primary/50">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-lg">
          <Brain className="h-5 w-5 text-primary" />
          AI Analysis
          <div className="flex gap-2 ml-auto">
            {post.difficulty && (
              <span className={`px-2 py-1 text-xs rounded-full ${
                post.difficulty === 'beginner' ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' :
                post.difficulty === 'intermediate' ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' :
                'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200'
              }`}>
                {post.difficulty}
              </span>
            )}
            <Button
              variant="ghost"
              size="sm"
              onClick={handleGenerateSummary}
              disabled={isGenerating}
            >
              {isGenerating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : post.summary ? (
                showSummary ? 'Hide' : 'Show'
              ) : (
                <>
                  <Zap className="h-4 w-4 mr-2" />
                  Generate
                </>
              )}
            </Button>
          </div>
        </CardTitle>
      </CardHeader>
      {showSummary && post.summary && (
        <CardContent>
          <p className="text-muted-foreground leading-relaxed">
            {post.summary}
          </p>
          <div className="mt-3 flex items-center justify-between text-xs text-muted-foreground">
            <span>Generated by AI • {post.summary.split(' ').length} words</span>
            {post.difficulty && (
              <span className="flex items-center gap-1">
                <Lightbulb className="h-3 w-3" />
                {post.difficulty} level
              </span>
            )}
          </div>
        </CardContent>
      )}
    </Card>
  );
};

export default AISummary;